### PR TITLE
Tree filter by due date

### PR DESCRIPTION
**Pull request by jo-tud**
This is an implementation of a tree filter by due date. It's complete with tests and artwork. It fixes issue #21. 
Please go ahead an merge it if you find it ok.

### CODE REVIEW

**Comment by funkyfuture** [comment]
actually, providing unittests instead of doctests would be highly appreciated.

**Comment by jo-tud** [comment]
Actually, I just copied the way the existing code was tested. So, both doctests and unit-tests are implemented. The unit tests are in testfile.py and test_filters_tree_controller.py
"This week" and "this month" is hard to test, because the result depends on today's date.

**Comment by funkyfuture** [comment]
i don't know whether and when [this branch](https://github.com/funkyfuture/QTodoTxt/tree/lib-task) will be merged, but i removed any doctests there. i see no sense to stick with 'em when we can have unittests.

you can also use `timedelta` in unittests.

**Comment by mNantern** [comment]
Hey @funkyfuture I don't have a PR for this branch, I thought you were still working on it !

Can you make a PR with that branch ?

Thank you.

**Comment by funkyfuture** [comment]
nah, i didn't want to open a pull request until things are viewable (see: https://github.com/mNantern/QTodoTxt/issues/94#issuecomment-69645263) and it's really tested in action.

also, i think it would be best if someone else reviews the api for inconsistencies and missing stuff. you know, when you looked a time on something, you will even miss the obvious…

**Pull request closed without merging**
