### PR TITLE
hyperlink for file:// protocol on linux

### PR DESCRIPTION
**Pull request by SimonChristopherCropper**
Incorporated regex in QTodoTxt that allows local resources on Linux to be referenced using the file:// hyperlink protocol.

See https://github.com/mNantern/QTodoTxt/issues/139

I have also included the regex for Windows files but have not had the time or computer to test.

### CODE REVIEW

**Comment by SimonChristopherCropper** [comment]
Incorporated regex for Windows file path. Hyperlinks appear in GUI interface but unable to test as I don't have a Windows Machine.

Create task "Test URL file://c:\temp\test.doc blah blah" to see the hyperlink. Click to see if Word opens. On Linux I can call LibreOffice and Text files easily.

**Comment by SimonChristopherCropper** [comment]
Ability to reference local files and directories (using **file://** as a prefix) and open an email in your email client (using **mailto:** as a prefix) have now been implemented. This is on top of the existing ability to reference webpages (using the **http://** prefix).

Note the **mailto:** protocol does not include trailing **//**. Although the using **mailto://** opens an email the email address name has the // preceding the actual address. This is a problem with xdg-open.

Functionality has been tested on Ubuntu 14.04 with Python 3 and xdg-open 1.0.2. Needs testing on Windows platform.

**Comment by mNantern** [comment]
Hi and thank you for your commit on QTT !

Can you add unittest for your PR ? We have a file called test_htmlizer that check various case on function task2html.

Thanks again !

**Comment by SimonChristopherCropper** [comment]
Update on unittest provided as requested. Please note that the test actually failed on your own URL hyperlink example. I discovered this because all my "hyperlink only" tasks did the same. The issue is that when only a hyperlink is processed it has a space inserted after the link. To resolve the FAIL issue using the test I included a space after the html tag. Alternatively, unless included by design, the html conversion routine should not insert a blank.

**Comment by SimonChristopherCropper** [comment]
Oh and by the way. Your contribution notes should reflect your desire to update the unittest routines ontop of doing syntax checks with flake8.

**Comment by SimonChristopherCropper** [comment]
Your current method of providing documentation is via markdown files. your wiki and README file in the main directory are out of sync (not current release). I extracted the wiki text and inserted in a documentation directory so the files can be tracked. I removed the home.md file as it is essentially a duplicate of the home.md on the wiki. I then created relative links rather than absolute links in the documentation section to avoid forked versions always pointing to the your main repository.

If you turn of the wiki link, the main README.md file acts as a landing page and directs the users to the correct pages anyway. The advantage is that you only have one set of files and the files changes can be tracked.

As an example I will also include changes to the documentation files to reflect my recent programming changes.

**Comment by mNantern** [comment]
Hey ! It looks like tests are not passing, can you see what's wrong ?

Thank you !

**Comment by mNantern** [comment]
Actually tests seem ok on local. I need to look at why Travis is failing.

**Comment by SimonChristopherCropper** [comment]
Hey mNantern have you established why Travis build does not work?

**Comment by kmicc** [comment]
This pull request also adds the wiki pages from the wiki to a subdirectory "documentation". There are advantages to do this, but there are also disadvantages, see https://github.com/mNantern/QTodoTxt/issues/141#issuecomment-157550193. I suggest NOT to merge the parts of this pull request related to including the documentation.

**Comment by kmicc** [comment]
Hello! I just tried your code. I think it would add a very useful functionality to QTodoTxt and I would like to add it to my own repository. Unfortunately, I figured out one issue. If you have a task description like ```do A and/or B```, it will be marked as ```file:///or```. I don't think this is a wanted behaviour. Would it be possible for you to change this?

**Comment by SimonChristopherCropper** [comment]
kmicc,

I have made the requested updates on my fork of the project. Hope that helps.

Cheers Simon

**Comment by kmicc** [comment]
Why did you close this pull request? I would have merged it into my repository, but there are still some issues.

1. When inserting more than one file, only the last one is linked.
2. When copying a file or a directory under linux with Thunar, there is an 0x0A (=LF) character appended to the file / directory url. Inserting such a string into a task description leads to *really* strange results. While this is clearly not your fault, this issue has to be fixed (ideally for all kinds of thinkable "bad" characters) before including your code into a productive used system.
3. I don't see a reason why the syntax for highlighting/linking directories is different from that for highlighting files.

As a workaround for issues 1 and 3 one can directly link a file or a directory using the following syntax in the task description:
```<a href="file-url">text_to_display</a>```

**Comment by SimonChristopherCropper** [comment]
As previously stated -- This repo appears inactive hence I closed the pull request. My changes are still available on my repo if you want to download them; If you have specific issues with my changes then you can post an issue on my fork. 

In regards to your concerns these limitations are with the original code (that is how mNatern decided to code the GUI), I can't see any obvious workaround without stripping the code back which I am unwilling to do this. Try contacting mNantern to see if he can help.

**Pull request closed without merging**
